version: '3.7'

services: 
  broker:
    build: 
      context: ./broker
      dockerfile: Dockerfile
    ports: 
      - 8000:443
    deploy:
      mode: replicated
      replicas: 2
    restart: always
  # subscriber:
  #   build: 
  #     context: ./subscriber
  #     dockerfile: Dockerfile
  #   restart: always